name: Deploy Document

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.1'
        registry-url: 'https://registry.npmjs.org'
    - name: Install and Build
      run: |
        yarn install
        yarn build
        yarn build:doc
    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@4.1.5
    #   with:
    #     branch: gh-pages
    #     folder: dist
    - name: Deploy Site
      uses: nogsantos/scp-deploy@master
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: "/app/nginx/www/doc.kwokronny.com/element-ui-saas-extend"