name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.1'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
    - run: yarn build:theme
    - run: yarn remove element-ui vue -D
    - run: yarn add element-ui vue -P
    - name: Set Env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Publish Package 
      run: |
        npm version $RELEASE_VERSION
        cat package.json
    # - run: npm publish --access public
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}